zero_test:
  desc: The type of classification to be performed
  value: seen #unseen seen_unseen all_with_text
epochs_c:
  desc: Number of epochs to train over
  value: 150
batch_size_c:
  desc: Size of each batch
  value: 128
lr_c:
  desc: Learning rate
  value: 0.005
num_classes_:
  desc: Number of classes to use
  value: 150  # Number of classes in CUB2011
test:
  desc: Number of classes to use
  value: false  # Number of classes in CUB2011
tau:
  desc: weight for seen classes. lower weight means lower importance
  value: 0.5  # Number of classes in CUB2011
randomness:
  desc: The probability of replacing visual by generated
  value: 1 # Number of classes in CUB2011
   


  