save_text_features: 'data/CUB_200_2011/mat/text/'
load_precomputed_text: False
#mat_file_text: 'data/xlsa17/data/CUB/text/att_splits.mat'
mat_file_text: 'data/xlsa17/data/CUB/att_splits.mat'
glove_dir: /project/data/glove.6B.50d.txt # /project/data/image_net/train
text_encoder: glove #albert #bart #albert  # prophet_net