epochs:
  desc: Number of epochs to train over
  value: 200
batch_size:
  desc: Size of each batch
  value: 256
lr:
  desc: Learning rate
  value: 0.005
num_classes:
  desc: Number of classes to use
  value: 150  # Number of classes in CUB2011
test:
  desc: Number of classes to use
  value: false  # Number of classes in CUB2011
   


  