epochs:
  desc: Number of epochs to train over
  value: 150
batch_size:
  desc: Size of each batch
  value: 128
lr:
  desc: Learning rate
  value: 0.005
num_classes:
  desc: Number of classes to use
  value: 100  # Number of classes in CUB2011
test:
  desc: Number of classes to use
  value: false  # Number of classes in CUB2011
tau:
  desc: weight for seen classes. lower weight means lower importance
  value: 1  # Number of classes in CUB2011
randomness:
  desc: The probability of replacing visual by generated
  value: 1 # Number of classes in CUB2011
   


  