epochs:
  desc: Number of epochs to train over
  value: 100
batchsize:
  desc: Size of each batch
  value: 256
lr:
  desc: Learning rate
  value: 0.0003
block_size:
  desc: Number of blocks
  value: 5
hidden_dims:
  desc: Number of hidden dims and their dimensions
  value: [2048]
permuter:
  desc: type of permutation
  value: LinearLU # manual reverse random manual
loss_type:
  desc: flow loss from IZF or GSMFlow
  value: IZFmean
flow_loss:
  desc: weight for the flow loss
  value: 2
centralizing_loss:
  desc: weight for the centralizing loss
  value: 1
mdd_loss:
  desc: weight for the mmd loss
  value: 0.1
prototype:
  desc: weight of the prototype loss
  value: 1
dataroot:
  desc: path to dataset
  value: 'data/data'
validation:
  desc: enable cross validation mode
  value: False
workers:
  desc: number of data loading workers
  value: 4
lr:
  desc: learning rate of flow
  value: 0.0003
weight_decay:
  desc:
  value: 1e-5
classifier_lr:
  desc: learning rate to train softmax classifier'
  value: 0.005
number_sample:
  desc: number features to generate per class
  value: 600
disp_interval:
  desc: interval
  value: 100
save_interval:
  desc: save inetrvak of checkpoint
  value: 10000
evl_interval:
  desc: eval interval
  value: 500
manualSeed:
  desc: manual seed
  value: 6400
semantic_vector_dim:
  desc: Dimension of semantic vectors
  value: 1024
  # value: 1024
pi:
  desc: degree of the perturbation
  value: 0
dropout:
  desc: probaility of droping dimension in he perturbation noise
  value: 0.0
gzsl:
  desc: The paradigm of zero-shot learning
  value: False
clusters:
  desc:
  value: 3
net:
  desc: type olf MLP
  value: MLP #MLPR # MLP
non_linearity:
  desc: non linear function for Affine Coupling
  value: leakyrelu #prelu # relu leakyrelu
act_norm:
  desc: presence of actnorm
  value: True
relative_positioning: 
  desc: relative positioning while training
  value: True
normalize_semantics:
  desc: To normalize semantics
  value: False
data_dir:
  desc: data directory
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_sentence_tf_idf_mean_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_sentence_weigthed_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_full_stop_bigram_7000_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_full_stop_bigram_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_5000_False.mat
  value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_7000_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_unfiltered_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_sentence_cleanedup_False.mat
  # value: data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_porter755_False.mat
  # 'data/CUB_200_2011/mat/resnet50d_proposed_split.txt_sentence_clean_whole.mat'
  # value: 'data/CUB_200_2011/mat/resnet50d_proposed_split_sentence_cleaner_whole_True.mat'
  # '
  # data/CUB_200_2011/mat/resnet50d_proposed_split.txt_sentence_len_clean.mat'
  # 'data/CUB_200_2011/mat/resnet50d_hard_split.txt_sentence_len.mat' #'data/CUB_200_2011/hard_split.txt'
  # value: 'data/CUB_200_2011/mat/resnet50d_albert.mat'
  # value: 'data/CUB_200_2011/mat/resnet50d_sentence_len_50.mat' # 'data/CUB_200_2011/mat/resnet50d_sentence_len.mat' # "  #/project/data/CUB_200_2011/mat/resnet50d_glove840B.mat" 
  # value: 'data/CUB_200_2011/mat/resnet50d_sentence_len.mat' # "  #/project/data/CUB_200_2011/mat/resnet50d_glove840B.mat" 