epochs:
  desc: Number of epochs to train over
  value: 21
batchsize:
  desc: Size of each batch
  value: 256
lr:
  desc: Learning rate
  value: 0.0003
block_size:
  desc: Number of blocks
  value: 5
hidden_dims:
  desc: Number of hidden dims and their dimensions
  value: [2048]
permuter:
  desc: type of permutation
  value: LinearLU # manual reverse random manual
loss_type:
  desc: flow loss from IZF or GSMFlow
  value: IZF
wt_f_l:
  desc: weight for the flow loss
  value: 2
wt_c_l:
  desc: weight for the centralizing loss
  value: 1
wt_mmd_l:
  desc: weight for the mmd loss
  value: 0.1
dataroot:
  desc: path to dataset
  value: 'data/data'
validation:
  desc: enable cross validation mode
  value: False
workers:
  desc: number of data loading workers
  value: 4
lr:
  desc: learning rate of flow
  value: 0.0003
weight_decay:
  desc:
  value: 1e-5
classifier_lr:
  desc: learning rate to train softmax classifier'
  value: 0.01
number_sample:
  desc: number features to generate per class
  value: 600
disp_interval:
  desc: interval
  value: 200
save_interval:
  desc: save inetrvak of checkpoint
  value: 10000
evl_interval:
  desc: eval interval
  value: 500
manualSeed:
  desc: manual seed
  value: 6400
semantic_vector_dim:
  desc: Dimension of semantic vectors
  value: 1024
prototype:
  desc: weight of the prototype loss
  value: 1
pi:
  desc: degree of the perturbation
  value: 0.05
dropout:
  desc: probaility of droping dimension in he perturbation noise
  value: 0.0
zsl:
  desc: The paradigm of zero-shot learning
  value: False
clusters:
  desc:
  value: 3

wt_p_l: 
  desc: weigth of prototype loss 
  value: 0
net:
  desc: type olf MLP
  value: MLP #MLPR # MLP
non_linearity:
  desc: non linear function for Affine Coupling
  value: leakyrelu #prelu # relu leakyrelu
minmax_rescale:
  desc: rescaling
  value: True
act_norm:
  desc: presence of actnorm
  value: True
relative_positioning: 
  desc: relative positioning while training
  value: True
model_name:
  desc: model name of text encoder
  value: albert-base-v2 # albert-xxlarge-v2
summary_extraction_mode:
  desc: type of extraction mode
  value: mean_tokens
aggregate_descriptions_method:
  desc: another aggregation
  value: mean_representations
aggregate_long_text_splits_method:
  desc: type of aggregation
  value: mean
overlap_window:
  desc: how much overlap between articles
  value: 3
max_length:
  desc: max length
  value: 20

   
