epochs:
  desc: Number of epochs to train over
  value: 60
batchsize:
  desc: Size of each batch
  value: 256
lr:
  desc: Learning rate
  value: 0.0003
block_size:
  desc: Number of blocks
  value: 5
hidden_dims:
  desc: Number of hidden dims
  value: 2
permuter:
  desc: type of permutation
  value: LinearLU # manual reverse random manual
loss_type:
  desc: flow loss from IZF or GSMFlow
  value: IZFmean
flow_loss:
  desc: weight for the flow loss
  value: 2
centralizing_loss:
  desc: weight for the centralizing loss
  value: 1
mdd_loss:
  desc: weight for the mmd loss
  value: 0.1
prototype:
  desc: weight of the prototype loss
  value: 0
dataroot:
  desc: path to dataset
  value: 'data/data'
validation:
  desc: enable cross validation mode
  value: False
workers:
  desc: number of data loading workers
  value: 4
lr:
  desc: learning rate of flow
  value: 0.0003
weight_decay:
  desc:
  value: 1e-2
classifier_lr:
  desc: learning rate to train softmax classifier'
  value: 0.005
number_sample:
  desc: number features to generate per class
  value: 300
disp_interval:
  desc: interval
  value: 27
save_interval:
  desc: save inetrvak of checkpoint
  value: 10000
evl_interval:
  desc: eval interval
  value: 27
semantic_vector_dim:
  desc: Dimension of semantic vectors
  value: 768
pi:
  desc: degree of the perturbation
  value: 0
dropout:
  desc: probaility of droping dimension in he perturbation noise
  value: 0.0
gzsl:
  desc: The paradigm of zero-shot learning
  value: True
clusters:
  desc:
  value: 3
net:
  desc: type olf MLP
  value: MLP #MLPR # MLP
non_linearity:
  desc: non linear function for Affine Coupling
  value: leakyrelu #prelu # relu leakyrelu
act_norm:
  desc: presence of actnorm
  value: True
relative_positioning: 
  desc: relative positioning while training
  value: True
normalize_semantics:
  desc: To normalize semantics
  value: False
data_dir:
  desc: data directory
  value: data/CUB_200_2011/mat/efficientnet_b3a_proposed_split_tfidf_5000_False.mat # data/CUB_200_2011/mat/resnet50d_proposed_split_tfidf_5000_False.mat