epochs:
  desc: Number of epochs to train over
  value: 31
batch_size:
  desc: Size of each batch
  value: 256
lr:
  desc: Learning rate
  value: 0.0005
block_size:
  desc: Number of blocks
  value: 5
hidden_dims:
  desc: Number of hidden dims and their dimensions
  value: [704,704,704]
permuter:
  desc: type of permutation
  value: LinearLU # manual reverse random manual
wt_f_l:
  desc: weight for the flow loss
  value: 2
wt_c_l:
  desc: weight for the centralizing loss
  value: 1
wt_mmd_l:
  desc: weight for the mmd loss
  value: 0.1
net:
  desc: type olf MLP
  value: MLP #MLPR # MLP
non_linearity:
  desc: non linear function for Affine Coupling
  value: prelu # relu leakyrelu
act_norm:
  desc: presence of actnorm
  value: true
dataset:
  desc: which dataset to use
  value: cub2011 #imagenet
cub2011_dir:
  desc: directory for cub2011
  value:
image_net_dir:
  desc: directory for Image Net
  value: /project/data/image_net/train
text_encoder:
  desc: which text encoder to use
  value: prophet_net
image_encoder:
  desc: pretrained weights
  value: efficientnet_b2
summary_extraction_mode:
  desc: type of extraction mode
  value: sum_tokens
aggregate_long_text_splits_method:
  desc: type of aggregation
  value: mean
aggregate_descriptions_method:
  desc: another aggregation
  value: sum_representations
overlap_window:
  desc: how much overlap between articles
  value: 5
max_length:
  desc: max length
  value: 10
zero_split:
  desc: what split is being used
  value: zsl_split_20


   
